apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "leartech-auth-admin-ui.fullname" . }}-config
  labels:
    {{- include "leartech-auth-admin-ui.labels" . | nindent 4 }}
data:
  api.conf.json: |
    {{- toJson .Values.config | nindent 4 }}
