apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leartech-auth-admin-ui.fullname" . }}
  labels:
    {{- include "leartech-auth-admin-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "leartech-auth-admin-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "leartech-auth-admin-ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/api.conf.json
              subPath: api.conf.json
              readOnly: true
            - name: runtime-config
              mountPath: /usr/share/nginx/html/assets/api.conf.json
              subPath: api.conf.json
              readOnly: true
      volumes:
        - name: runtime-config
          configMap:
            name: {{ include "leartech-auth-admin-ui.fullname" . }}-config
